import os
from dotenv import load_dotenv

load_dotenv(dotenv_path="config/.env")

base_dir = os.path.dirname(os.path.abspath(__file__))

PROJECT_NAME = "digital-twin-chile-x"
INCLUDE_PROFILE_INFORMATION = (
    True  # NOTE: SET THIS TRUE OR FALSE FOR EACH VARIANT EXECUTION
)
ENABLE_WEB_SEARCH = True  # NOTE: SET THIS TRUE OR FALSE FOR EACH VARIANT EXECUTION
PIPELINE_EXECUTION_DATE = "pilot_"

if ENABLE_WEB_SEARCH and INCLUDE_PROFILE_INFORMATION:
    PIPELINE_EXECUTION_DATE += "with_profile_info_with_web_search"
elif ENABLE_WEB_SEARCH and not INCLUDE_PROFILE_INFORMATION:
    PIPELINE_EXECUTION_DATE += "without_profile_info_with_web_search"
elif not ENABLE_WEB_SEARCH and INCLUDE_PROFILE_INFORMATION:
    PIPELINE_EXECUTION_DATE += "with_profile_info_without_web_search"
else:
    PIPELINE_EXECUTION_DATE += "without_profile_info_without_web_search"

PROFILE_SEARCH_START_DATE = "01-01-2000"  # MM-DD-YYYY format
PROFILE_SEARCH_END_DATE = "12-31-2025"  # MM-DD-YYYY format
WEB_SEARCH_COUNTRY = "CL"
NUM_POSTS_PER_PROFILE = 100
PROFILE_METADATA_SEARCH_FILE = f"profile_metadata_{PIPELINE_EXECUTION_DATE}.csv"
PROFILE_SEARCH_FILE = f"profile_search_{PIPELINE_EXECUTION_DATE}.csv"
POST_ENTITY_GEOGRAPHIC_INTERVIEW_FILE = (
    f"post_entity_geographic_interview_{PIPELINE_EXECUTION_DATE}.csv"
)
POST_VOTING_PREFERENCE_WO_VOTING_RESULTS_INTERVIEW_FILE = (
    f"post_voting_preference_interview_wo_voting_results_{PIPELINE_EXECUTION_DATE}.csv"
)
POST_VOTING_PREFERENCE_WITH_VOTING_RESULTS_INTERVIEW_FILE = f"post_voting_preference_interview_with_voting_results_{PIPELINE_EXECUTION_DATE}.csv"

ENTITY_GEOGRAPHIC_INTERVIEW_REGEX_PATTERNS = [
    r"^PERSONA REAL.*\-\s*explanation$",
    r"^PERSONA REAL.*\-\s*symbol$",
    r"^PERSONA REAL.*\-\s*category$",
    r"^PERSONA REAL.*\-\s*speculation$",
    r"^PERSONA QUE VIVE EN CHILE.*\-\s*explanation$",
    r"^PERSONA QUE VIVE EN CHILE.*\-\s*symbol$",
    r"^PERSONA QUE VIVE EN CHILE.*\-\s*category$",
    r"^PERSONA QUE VIVE EN CHILE.*\-\s*speculation$",
    r"^REGIÓN.*\-\s*explanation$",
    r"^REGIÓN.*\-\s*symbol$",
    r"^REGIÓN.*\-\s*category$",
    r"^REGIÓN.*\-\s*speculation$",
    r"^COMUNA.*\-\s*explanation$",
    r"^COMUNA.*\-\s*symbol$",
    r"^COMUNA.*\-\s*category$",
    r"^COMUNA.*\-\s*speculation$",
]

VOTING_PREFERENCE_INTERVIEW_WO_VOTING_RESULTS_REGEX_PATTERNS = [
    r"^EDAD.*\-\s*symbol$",
    r"^EDAD.*\-\s*category$",
    r"^EDAD.*\-\s*speculation$",
    r"^EDAD.*\-\s*explanation$",
    r"^SEXO.*\-\s*symbol$",
    r"^SEXO.*\-\s*category$",
    r"^SEXO.*\-\s*speculation$",
    r"^SEXO.*\-\s*explanation$",
    r"^RANGO DE INGRESOS PERSONALES.*\-\s*symbol$",
    r"^RANGO DE INGRESOS PERSONALES.*\-\s*category$",
    r"^RANGO DE INGRESOS PERSONALES.*\-\s*speculation$",
    r"^RANGO DE INGRESOS PERSONALES.*\-\s*explanation$",
    r"^RANGO DE INGRESOS DEL HOGAR.*\-\s*symbol$",
    r"^RANGO DE INGRESOS DEL HOGAR.*\-\s*category$",
    r"^RANGO DE INGRESOS DEL HOGAR.*\-\s*speculation$",
    r"^RANGO DE INGRESOS DEL HOGAR.*\-\s*explanation$",
    r"^ESTADO CIVIL.*\-\s*symbol$",
    r"^ESTADO CIVIL.*\-\s*category$",
    r"^ESTADO CIVIL.*\-\s*speculation$",
    r"^ESTADO CIVIL.*\-\s*explanation$",
    r"^CALIFICACIÓN EDUCATIVA MÁS ALTA.*\-\s*symbol$",
    r"^CALIFICACIÓN EDUCATIVA MÁS ALTA.*\-\s*category$",
    r"^CALIFICACIÓN EDUCATIVA MÁS ALTA.*\-\s*speculation$",
    r"^CALIFICACIÓN EDUCATIVA MÁS ALTA.*\-\s*explanation$",
    r"^OCUPACIÓN ACUTAL.*\-\s*symbol$",
    r"^OCUPACIÓN ACUTAL.*\-\s*category$",
    r"^OCUPACIÓN ACUTAL.*\-\s*speculation$",
    r"^OCUPACIÓN ACUTAL.*\-\s*explanation$",
    r"^ORIENTACIÓN IDEOLÓGICA O POLÍTICA.*\-\s*symbol$",
    r"^ORIENTACIÓN IDEOLÓGICA O POLÍTICA.*\-\s*category$",
    r"^ORIENTACIÓN IDEOLÓGICA O POLÍTICA.*\-\s*speculation$",
    r"^ORIENTACIÓN IDEOLÓGICA O POLÍTICA.*\-\s*explanation$",
    r"^PARTIDO POLÍTICO.*\-\s*symbol$",
    r"^PARTIDO POLÍTICO.*\-\s*category$",
    r"^PARTIDO POLÍTICO.*\-\s*speculation$",
    r"^PARTIDO POLÍTICO.*\-\s*explanation$",
    r"^AFINIDAD CON PARTIDO POLÍTICO.*\-\s*value$",
    r"^AFINIDAD CON PARTIDO POLÍTICO.*\-\s*speculation$",
    r"^AFINIDAD CON PARTIDO POLÍTICO.*\-\s*explanation$",
    r"^INTERÉS EN LA POLÍTICA.*\-\s*symbol$",
    r"^INTERÉS EN LA POLÍTICA.*\-\s*category$",
    r"^INTERÉS EN LA POLÍTICA.*\-\s*speculation$",
    r"^INTERÉS EN LA POLÍTICA.*\-\s*explanation$",
    r"^ATENCIÓN CAMPAÑA 2025.*\-\s*symbol$",
    r"^ATENCIÓN CAMPAÑA 2025.*\-\s*category$",
    r"^ATENCIÓN CAMPAÑA 2025.*\-\s*speculation$",
    r"^ATENCIÓN CAMPAÑA 2025.*\-\s*explanation$",
    r"^ATENCIÓN CAMPAÑA 2021.*\-\s*symbol$",
    r"^ATENCIÓN CAMPAÑA 2021.*\-\s*category$",
    r"^ATENCIÓN CAMPAÑA 2021.*\-\s*speculation$",
    r"^ATENCIÓN CAMPAÑA 2021.*\-\s*explanation$",
    r"^CONFIANZA GENERAL EN OTRAS PERSONAS.*\-\s*symbol$",
    r"^CONFIANZA GENERAL EN OTRAS PERSONAS.*\-\s*category$",
    r"^CONFIANZA GENERAL EN OTRAS PERSONAS.*\-\s*speculation$",
    r"^CONFIANZA GENERAL EN OTRAS PERSONAS.*\-\s*explanation$",
    r"^(INDV) VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES LEGISLATIVAS DE CHILE DE 2021.*\-\s*symbol$",
    r"^(INDV) VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES LEGISLATIVAS DE CHILE DE 2021.*\-\s*category$",
    r"^(INDV) VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES LEGISLATIVAS DE CHILE DE 2021.*\-\s*speculation$",
    r"^(INDV) VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES LEGISLATIVAS DE CHILE DE 2021.*\-\s*explanation$",
    r"^(INDV) VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES LEGISLATIVAS DE CHILE DE 2021.*\-\s*symbol$",
    r"^(INDV) VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES LEGISLATIVAS DE CHILE DE 2021.*\-\s*category$",
    r"^(INDV) VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES LEGISLATIVAS DE CHILE DE 2021.*\-\s*speculation$",
    r"^(INDV) VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES LEGISLATIVAS DE CHILE DE 2021.*\-\s*explanation$",
    r"^VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*symbol$",
    r"^VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*category$",
    r"^VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*speculation$",
    r"^VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*explanation$",
    r"^VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*symbol$",
    r"^VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*category$",
    r"^VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*speculation$",
    r"^VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*explanation$",
    r"^(INDV) PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*symbol$",
    r"^(INDV) PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*category$",
    r"^(INDV) PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*speculation$",
    r"^(INDV) PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*explanation$",
    r"^(INDV) PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*symbol$",
    r"^(INDV) PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*category$",
    r"^(INDV) PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*speculation$",
    r"^(INDV) PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*explanation$",
    r"^INDECISIÓN EN TORNO A LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*symbol$",
    r"^INDECISIÓN EN TORNO A LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*category$",
    r"^INDECISIÓN EN TORNO A LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*speculation$",
    r"^INDECISIÓN EN TORNO A LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*explanation$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO JOSÉ ANTONIO KAST.*\-\s*symbol$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO JOSÉ ANTONIO KAST.*\-\s*category$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO JOSÉ ANTONIO KAST.*\-\s*speculation$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO JOSÉ ANTONIO KAST.*\-\s*explanation$",
    r"^FAVORABILIDAD DE LA CANDIDATA PRESIDENCIAL CHILENA JEANNETTE JARA.*\-\s*symbol$",
    r"^FAVORABILIDAD DE LA CANDIDATA PRESIDENCIAL CHILENA JEANNETTE JARA.*\-\s*category$",
    r"^FAVORABILIDAD DE LA CANDIDATA PRESIDENCIAL CHILENA JEANNETTE JARA.*\-\s*speculation$",
    r"^FAVORABILIDAD DE LA CANDIDATA PRESIDENCIAL CHILENA JEANNETTE JARA.*\-\s*explanation$",
    r"^FAVORABILIDAD DE LA CANDIDATA PRESIDENCIAL CHILENA EVELYN MATTHEI.*\-\s*symbol$",
    r"^FAVORABILIDAD DE LA CANDIDATA PRESIDENCIAL CHILENA EVELYN MATTHEI.*\-\s*category$",
    r"^FAVORABILIDAD DE LA CANDIDATA PRESIDENCIAL CHILENA EVELYN MATTHEI.*\-\s*speculation$",
    r"^FAVORABILIDAD DE LA CANDIDATA PRESIDENCIAL CHILENA EVELYN MATTHEI.*\-\s*explanation$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO FRANCO PARISI.*\-\s*symbol$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO FRANCO PARISI.*\-\s*category$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO FRANCO PARISI.*\-\s*speculation$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO FRANCO PARISI.*\-\s*explanation$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO MARCO ENRÍQUEZ-OMINAMI.*\-\s*symbol$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO MARCO ENRÍQUEZ-OMINAMI.*\-\s*category$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO MARCO ENRÍQUEZ-OMINAMI.*\-\s*speculation$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO MARCO ENRÍQUEZ-OMINAMI.*\-\s*explanation$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO EDUARDO ARTÉS.*\-\s*symbol$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO EDUARDO ARTÉS.*\-\s*category$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO EDUARDO ARTÉS.*\-\s*speculation$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO EDUARDO ARTÉS.*\-\s*explanation$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO JOHANNES KAISER.*\-\s*symbol$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO JOHANNES KAISER.*\-\s*category$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO JOHANNES KAISER.*\-\s*speculation$",
    r"^FAVORABILIDAD DEL CANDIDATO PRESIDENCIAL CHILENO JOHANNES KAISER.*\-\s*explanation$",
    r"^CREENCIA SOBRE EL TEMA MÁS IMPORTANTE ACTUALMENTE.*\-\s*symbol$",
    r"^CREENCIA SOBRE EL TEMA MÁS IMPORTANTE ACTUALMENTE.*\-\s*category$",
    r"^CREENCIA SOBRE EL TEMA MÁS IMPORTANTE ACTUALMENTE.*\-\s*speculation$",
    r"^CREENCIA SOBRE EL TEMA MÁS IMPORTANTE ACTUALMENTE.*\-\s*explanation$",
    r"^PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025 SI LAS ELECCIONES SE CELEBRARAN EN LA FECHA DE SU ÚLTIMO TUIT.*\-\s*symbol$",
    r"^PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025 SI LAS ELECCIONES SE CELEBRARAN EN LA FECHA DE SU ÚLTIMO TUIT.*\-\s*category$",
    r"^PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025 SI LAS ELECCIONES SE CELEBRARAN EN LA FECHA DE SU ÚLTIMO TUIT.*\-\s*speculation$",
    r"^PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025 SI LAS ELECCIONES SE CELEBRARAN EN LA FECHA DE SU ÚLTIMO TUIT.*\-\s*explanation$",
]

# VOTING_PREFERENCE_INTERVIEW_WITH_VOTING_RESULTS_REGEX_PATTERNS = [
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*symbol$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*category$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*speculation$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*explanation$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*symbol$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*category$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*speculation$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2021.*\-\s*explanation$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES LEGISLATIVAS DE CHILE 2021.*\-\s*symbol$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES LEGISLATIVAS DE CHILE 2021.*\-\s*category$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES LEGISLATIVAS DE CHILE 2021.*\-\s*speculation$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES LEGISLATIVAS DE CHILE 2021.*\-\s*explanation$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES LEGISLATIVAS DE CHILE DE 2021.*\-\s*symbol$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES LEGISLATIVAS DE CHILE DE 2021.*\-\s*category$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES LEGISLATIVAS DE CHILE DE 2021.*\-\s*speculation$",
#     r"^VOTACIÓN ANTERIOR\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES LEGISLATIVAS DE CHILE DE 2021.*\-\s*explanation$",
#     r"^PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*symbol$",
#     r"^PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*category$",
#     r"^PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*speculation$",
#     r"^PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sPARTICIPACIÓN EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*explanation$",
#     r"^PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*symbol$",
#     r"^PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*category$",
#     r"^PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*speculation$",
#     r"^PREFERENCIAS DE VOTACIÓN ACTUALES\s[-–—]\sOPCIÓN DE VOTO EN LAS ELECCIONES PRESIDENCIALES DE CHILE DE 2025.*\-\s*explanation$",
# ]
